use_default_settings: true

server:
  secret_key: "${SEARXNG_SECRET}"
  limiter: false
  image_proxy: true

ui:
  static_use_hash: true

search:
  safe_search: 0
  autocomplete: ""
  formats:
    - html
    - json
